# Default values for helm-webapp-cve-processor.
image:
  initContainer:
    repository: niteshmore22/webapp-cve-processor-db
    pullPolicy: Always
    tag: "latest"
  mainContainer:
    repository: niteshmore22/webapp-cve-processor
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

configMap:
  db_port: "5432"
  db_name: cve
  db_schemas : cve
  cve_url: "https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip"


secrets:
  type: Opaque

nameSpace: "csye7125"

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ZW50ZXJ5b3VydXNlcm5hbWVwYXNzd29yZA==

nameOverride: ""
fullnameOverride: "cve-processor"

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   memory: 256Mi
   cpu: 500m

postgresql:
  namespace: default
  auth:
    username: "db_user"
    password: "db_password"
    database: "cve"
  primary:
    persistence:
      enabled: true
      storageClass: ebs-sc
      accessModes:
        - ReadWriteMany
      size: 8Gi
      labels: 
        app: cve-processor-db
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: "512Mi"
        cpu: "500m"
        
kmsKeyId: "The full ARN of the key"
storageClass:
  parameters:
    type: gp3
    fstype: ext4
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

job:
  spec:
    parallelism: 1
    completions: 1