# Default values for helm-webapp-cve-processor.
image:
  mainContainer:
    repository: niteshmore22/webapp-cve-processor
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

configMap:
  cve_url: https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip
  kafka_topic: cve
  kafka_brokers: 
    - cve-kafka-controller-0.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092
    - cve-kafka-controller-1.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092
    - cve-kafka-controller-2.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092

secrets:
  type: Opaque
  kafka_username: archops_admin
  kafka_password: ArchOps@670951

nameSpace: cve-processor

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ewoiYXV0aHMiOnsKImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6ewoiYXV0aCI6ImJtbDBaWE5vYlc5eVpUSXlPbVJqYTNKZmNHRjBYeTFsV1d0MlJrdzFSVTVXUjJwVVZFdDBUMnBaV1c5SVZVdzJOQT09Igp9Cn0KfQ==

nameOverride: ""
fullnameOverride: cve-processor

resources: 
  limits:
    cpu: 0.8
    memory: 768Mi
  requests:
    cpu: 0.5
    memory: 512Mi

job:
  spec:
    parallelism: 1
    completions: 1