# Default values for helm-webapp-cve-processor.
image:
  initContainer:
    repository: niteshmore22/cve_db
    pullPolicy: Always
    tag: "latest"
  mainContainer:
    repository: niteshmore22/webapp-cve-processor
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

configMap:
  db_host: db_host_name
  db_port: "5432"
  db_name: cve
  db_url: "jdbc:postgresql://db_host_name:5432/cve"
  db_schemas : cve
  cve_url: "https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip"

secrets:
  db_user: "db_user_name"
  db_password: "db_password"
  type: Opaque

nameSpace: "csye7125"

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ZW50ZXJ5b3VydXNlcm5hbWVwYXNzd29yZA==

nameOverride: ""
fullnameOverride: "cve-processor"

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   memory: 256Mi
   cpu: 500m
