# Default values for helm-webapp-cve-processor.
nameOverride: ""
fullnameOverride: cve-processor
namespace: cve-processor

podLabels: 
  app: cve-processor
  service: kafka-producer

image:
  mainContainer:
    repository: niteshmore22/webapp-cve-processor
    pullPolicy: Always
    tag: "latest"

configMap:
  cve_url: https://github.com/CVEProject/cvelistV5/archive/refs/heads/main.zip
  kafka_topic: cve
  kafka_brokers: 
    - localhost:9092
    - localhost:9093
    - localhost:9094

secrets:
  type: Opaque
  kafka_username: archops_admin
  kafka_password: ArchOps@670951

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ZW50ZXJ5b3VydXNlcm5hbWVwYXNzd29yZA==

resources: 
  limits:
    cpu: 1
    memory: 768Mi
  requests:
    cpu: 0.5
    memory: 512Mi

job:
  spec:
    parallelism: 1
    completions: 1