---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Values.nameSpace }}
type: {{ .Values.imagePullSecrets.type }}
