---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
spec:
  imagePullSecrets:
    - name: {{ .Release.Name }}-regcred
  initContainers:
    - name: init-cve-db
      image: "{{ .Values.image.initContainer.repository }}:{{ .Values.image.initContainer.tag }}"
      imagePullPolicy: {{ .Values.image.initContainer.pullPolicy }}
      env:
        - name: db_host
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: db_host
        - name: db_port
          valueFrom:
            configMapKeyRef:
              name:  {{ .Release.Name }}-cm
              key: db_port
        - name: db_name
          valueFrom:
            configMapKeyRef:
              name:  {{ .Release.Name }}-cm
              key: db_name
        - name: db_url
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: db_url
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secrets
              key: db_user
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secrets
              key: db_password
        - name: db_schemas
          valueFrom:
            configMapKeyRef:
              name:  {{ .Release.Name }}-cm
              key: db_schemas
  containers:
    - name: webapp-cve-processor
      image: "{{ .Values.image.mainContainer.repository }}:{{ .Values.image.mainContainer.tag }}"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: {{ .Values.resources.limits.memory }}
          cpu: {{ .Values.resources.limits.cpu }}
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-cm
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name:  {{ .Release.Name }}-cm
              key: db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name:  {{ .Release.Name }}-cm
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secrets
              key: db_password      